# Generated by Django 4.2.28 on 2026-02-14 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def create_default_workshop(apps, schema_editor):
    """Создаём цех по умолчанию и привязываем к нему все существующие записи."""
    Workshop = apps.get_model('sklad', 'Workshop')
    Item = apps.get_model('sklad', 'Item')
    Supply = apps.get_model('sklad', 'Supply')
    workshop, _ = Workshop.objects.get_or_create(name='Основной цех', defaults={'id': uuid.uuid4()})
    Item.objects.filter(workshop__isnull=True).update(workshop=workshop)
    Supply.objects.filter(workshop__isnull=True).update(workshop=workshop)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sklad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='supply',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sklad.workshop'),
        ),
        migrations.AddField(
            model_name='supply',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='sklad.workshop'),
        ),
        migrations.CreateModel(
            name='WorkshopUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='sklad.workshop')),
            ],
            options={
                'unique_together': {('workshop', 'user')},
            },
        ),
        migrations.RunPython(create_default_workshop, migrations.RunPython.noop),
    ]
