# Generated by Django 4.2.28 on 2026-02-14 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_workshop_user_to_profile(apps, schema_editor):
    WorkshopUser = apps.get_model('sklad', 'WorkshopUser')
    UserProfile = apps.get_model('sklad', 'UserProfile')
    for wu in WorkshopUser.objects.select_related('user', 'workshop'):
        UserProfile.objects.get_or_create(user=wu.user, defaults={'workshop': wu.workshop})


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sklad', '0002_add_workshop_multi_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='sklad.workshop')),
            ],
        ),
        migrations.RunPython(migrate_workshop_user_to_profile, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='WorkshopUser',
        ),
    ]
