# Generated by Django 4.2.28 on 2026-02-14 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sklad', '0003_user_profile_workshop'),
    ]

    operations = [
        migrations.RenameModel(old_name='UserProfile', new_name='WorkshopAssignment'),
        migrations.AlterField(
            model_name='workshopassignment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_assignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
