# Generated by Django 6.0.2 on 2026-02-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0006_alter_workshopassignment_workshop'),
        ('sklad', '0008_item_wb_url_ozon_url'),
    ]

    operations = [
    ]
